---
- name: Provision and configure Flask_App
  hosts: webservers
  become: yes

  tasks:
    - name: Start Flask App on ubuntu
      command: "nohup python3 /home/ubuntu/Flask-Web-App-Project
           /app.py"
      async: 100
      poll: 0
      become_user: "{{ ansible_user }}"
      when: ansible_distribution == "ubuntu"

    - name: Start Flask App on Ubuntu
      command: "nohup python3 /home/ubuntu/Flask-Web-App-Project
               /app.py"
      async: 100
      poll: 0
      become_user: "{{ ansible_user }}"
      when: ansible_distribution == 'Ubuntu'
...